title: PE501091200-2024
description: "Resultados del proyecto: Monitoreo del crecimiento urbano en zonas vulnerables empleando imágenes satelitales e inteligencia artificial."
baseurl: "/PE501091200-2024"  # Ruta después del dominio
url: "https://9javi9.github.io"         # Dominio base de GitHub Pages

remote_theme: just-the-docs/just-the-docs

repository_url: https://github.com/9javi9/PE501091200-2024
repository_branch: main
search_enabled: true
aux_links:
  "Reportar problema":
    - https://github.com/9javi9/PE501091200-2024/issues

head:
  - "<link rel='stylesheet' href='https://unpkg.com/leaflet@1.7.1/dist/leaflet.css' />"
  - "<script src='https://unpkg.com/leaflet@1.7.1/dist/leaflet.js'></script>"

# Opcional: orden de navegación
nav_sort: case_sensitive

markdown: kramdown 
highlighter: rouge

plugins:
  - jekyll-feed

footer_content: footer_custom

just_the_docs:
  color_scheme: pucp
  custom_css:
    - assets/css/custom.css
